Added the image cleanup workflow
Calance-US/calance-workflows pull request #17
Opened 2022-12-29 12:52 UTC by nmathur478

2022-12-30 06:36 UTC, agoyalcalance requested changes

2022-12-30 06:36 UTC, agoyalcalance commented on .github/workflows/clean-images.yml
> +          org-name: calance
org-name value does not seem okay.

2022-12-30 06:36 UTC, agoyalcalance commented on .github/workflows/clean-images.yml
> +          cut-off: One month ago UTC
are we sure that one month ago works.. in case of dimensions 1 month may result in a much larger size consumption.

2023-01-03 08:46 UTC, nmathur478 commented on .github/workflows/clean-images.yml
> +          org-name: calance
I will change the account type to personal then.

2023-01-03 08:48 UTC, nmathur478 commented on .github/workflows/clean-images.yml
> +          cut-off: One month ago UTC
Let me know the cutoff required for the Prod env. I will be updating it then.

2023-01-03 09:59 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +          cut-off: One month ago UTC
@agoyalcalance dimensions dont use GHCR if i remember correctly? (this only cleans up container images)

2023-01-03 10:03 UTC, nmathur478 commented on .github/workflows/clean-images.yml
> +          cut-off: One month ago UTC
Sure @ypmittal 
Thank you for letting me know.

2023-01-04 06:50 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +    inputs:
please add inputs as mentioned in the task description
https://project.calance.work/projects/ci-slash-cd-workflows/work_packages/92/activity

2023-01-04 12:35 UTC, nmathur478 commented on .github/workflows/clean-images.yml
> +    inputs:
Made the required changes @ypmittal

2023-01-04 12:48 UTC, agoyalcalance commented on .github/workflows/clean-images.yml
> +
why are there couple of additional lines here.

2023-01-05 05:27 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +
please delete extra new empty lines at the end
only a `newline` char should be there at the end

2023-01-05 05:28 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +          filter_tags: "rc*"
does this work? have we tested this whole workflow somehow?
disuss with arpit or me if you dont know how

2023-01-05 05:29 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +      minimum_images_prod:
please use the names as specified in the task description

2023-01-05 05:29 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +      minimum_images_prod:
for example, this should be renamed to prod_keep_at_least

2023-01-05 05:31 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +name: Delete old container images
rename to `Clean Image Registry`
also rename file to `clean-image-registry.yml`

2023-01-05 05:36 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +          token: ${{ secrets.GHCR_TOKEN }}
does this secret get picked up from org secrets automatically?
or the does the calling workflow has to pass this? 
please verify and let me know

2023-01-06 09:25 UTC, ypmittal commented on .github/workflows/clean-image-registry.yml
> +      cutoff_prod:
please change cutoff input names according to the task description as well

2023-01-06 09:26 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +name: Delete old container images
@nmathur478 name value is still not changed

2023-01-06 09:27 UTC, ypmittal commented on .github/workflows/clean-images.yml
> +          filter_tags: "rc*"
have you tested this? please reply here with the link where you tested

2023-02-23 11:49 UTC, ypmittal requested changes
Please add a newline char at the end of the file

also get it reviewed by @agoyalcalance

2023-02-24 07:51 UTC, ypmittal approved these changes
LGTM

2023-02-24 10:36 UTC, agoyalcalance requested changes
just one comment added.

2023-02-24 10:36 UTC, agoyalcalance commented on .github/workflows/clean-image-registry.yml
> +      MS_TEAMS_WEBHOOK_URI:
how are these Webhook URI's configured.. that should happen through our standard service accounts @nmathur478 @ypmittal.

2023-02-24 11:12 UTC, merged