adding support for build time env vars
Calance-US/calance-workflows pull request #18
Opened 2023-01-24 08:11 UTC by hsachan22

2023-01-31 13:41 UTC, ypmittal commented on .github/workflows/build.yml
> +      test_env_vars:
lets rename both to 
dot_env_file_testing
dot_env_file_production

2023-01-31 13:42 UTC, ypmittal commented on .github/workflows/build.yml
> +        run: |
this step should only run when either one of the inputs is non-empty
otherwise we might end up overwriting a .env file that is meant for run-time env vars (like in backend projects)

2023-01-31 13:43 UTC, ypmittal requested changes
Please address the comments

2023-01-31 13:49 UTC, ypmittal commented on .github/workflows/build.yml
>            if [[ "${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version']}}" =~ .*-rc[0-9] ]]; then
we should use the output of the previous step 
so that the logic for matching tag pattern is not repeated (DRY principle)

2023-02-01 05:40 UTC, hsachan22 commented on .github/workflows/build.yml
> +      test_env_vars:
Done

2023-02-01 05:41 UTC, hsachan22 commented on .github/workflows/build.yml
> +        run: |
Done

2023-02-01 05:41 UTC, hsachan22 commented on .github/workflows/build.yml
>            if [[ "${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version']}}" =~ .*-rc[0-9] ]]; then
Done

2023-02-01 06:21 UTC, ypmittal approved these changes
LGTM

2023-02-01 06:23 UTC, merged