adding custom action for setting cluster_environment
Calance-US/calance-workflows pull request #19
Opened 2023-01-24 12:50 UTC by hsachan22

2023-01-31 13:46 UTC, ypmittal commented on actions/cluster-env-setter/package.json
> +  "name": "cluster-env-setter",
please add the usage of this action inside our workflows within this PR

2023-01-31 13:49 UTC, ypmittal requested changes
address the 1 change requested

2023-02-01 06:11 UTC, hsachan22 commented on actions/cluster-env-setter/package.json
> +  "name": "cluster-env-setter",
Done

2023-02-16 06:55 UTC, ypmittal commented on actions/cluster-env-setter/index.js
> +  const isTesting = imageVersion.match(/.*-rc[0-9]/)
default should be testing.
i.e. we should assign production namespace if and only if a production tag is pushed

2023-02-17 13:09 UTC, ypmittal approved these changes
LGTM

2023-02-17 13:09 UTC, merged