1 created reusable workflow for triggering jenkins job
Calance-US/calance-workflows pull request #2
Opened 2022-09-15 09:10 UTC by ppsinghcalance

2022-09-15 10:33 UTC, agoyalcalance requested changes
@ppsinghcalance i understand this in draft state.. however still attaching my feedbacks.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/build.yml
>        namespace: ${{ secrets.NAMESPACE }}
let's put upper case parameter - NAMESPACE to maintain consistency.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/build.yml
> +    uses: Calance-US/calance-workflows/.github/workflows/deploy.yml@test
this will become main branch.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/deploy.yml
>          uses: prempratap09/build-jenkins-job@master
this is still using repository from your personal namespace. it should utilise Calance-US repository.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/deploy.yml
> +        description: 'Jenkins USER'
the description should be `Jenkins TOKEN` not `Jenkins USER`.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/deploy.yml
>        namespace:
this namespace should also be in uppercase.

2022-09-15 10:33 UTC, agoyalcalance commented on .github/workflows/build.yml
> +#  deploy-to-kubernetes:
remove commented out lines.

2022-09-15 13:18 UTC, agoyalcalance commented on .github/workflows/build.yml
> +        description: 'Jenkins USER'
same the description should be Jenkins TOKEN.

2022-09-15 17:55 UTC, ppsinghcalance commented on .github/workflows/build.yml
>        namespace: ${{ secrets.NAMESPACE }}
changed the code

2022-09-15 17:57 UTC, ppsinghcalance commented on .github/workflows/build.yml
> +    uses: Calance-US/calance-workflows/.github/workflows/deploy.yml@test
removed the code, using the same in public-repository-template

2022-09-15 17:58 UTC, ppsinghcalance commented on .github/workflows/deploy.yml
>          uses: prempratap09/build-jenkins-job@master
changed to Calance-US repository.

2022-09-15 17:59 UTC, ppsinghcalance commented on .github/workflows/deploy.yml
> +        description: 'Jenkins USER'
Changed to Jenkins Token

2022-09-15 18:02 UTC, ppsinghcalance commented on .github/workflows/deploy.yml
>        namespace:
made it uppercase

2022-09-15 18:02 UTC, ppsinghcalance commented on .github/workflows/build.yml
> +#  deploy-to-kubernetes:
done

2022-09-15 18:03 UTC, ppsinghcalance commented on .github/workflows/build.yml
> +        description: 'Jenkins USER'
removed the piece of code form build.yml

2022-09-16 05:35 UTC, agoyalcalance approved these changes

2022-09-16 05:38 UTC, merged